version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adl123
    volumes:
    - db-volume:/var/lib/postgresql/data

  api:
    image: curso/curso
    environment:
      DB_HOST: database
    ports:
      - "8081:8081"
volumes:
  db-volume: