version: '3'
#
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cursos
    volumes:
    - db-volume:/var/lib/postgresql/data

  api:
    image: curso/curso
    environment:
      DB_HOST: database
    ports:
      - "8080:8080"
volumes:
  db-volume: